In [1]:
import pandas as pd 
import xlrd 
import os 
import re

In [2]:
os.listdir()

['jp_FoodG_male_2012.xlsx',
 'jp_FoodG_female_2017.xlsx',
 'jp_FoodG_total_2016.xlsx',
 'jp_FoodG_total_2017.xlsx',
 '.DS_Store',
 'jp_FoodG_female_2016.xlsx',
 'jp_FoodG_male_2013.xlsx',
 'jp_FoodG_female_2011.xlsx',
 'jp_FoodG_male_2014.xlsx',
 'jp_FoodG_total_2010.xls',
 'jp_FoodG_male_2015.xlsx',
 'jp_FoodG_total_2011.xlsx',
 'jp_FoodG_total_2012.xlsx',
 'jp_FoodG_female_2013.xlsx',
 'jp_FoodG_male_2016.xlsx',
 'jp_FoodG_male_2017.xlsx',
 'JP_FoodGIntakeURLParsing.ipynb',
 'jp_FoodG_female_2012.xlsx',
 'jp_FoodG_total_2013.xlsx',
 '.ipynb_checkpoints',
 'jp_FoodG_total_2014.xlsx',
 'jp_FoodG_male_2010.xls',
 'jp_FoodG_female_2015.xlsx',
 'jp_FoodG_female_2014.xlsx',
 'jp_FoodG_total_2015.xlsx',
 'jp_FoodG_female_2010.xls',
 'jp_FoodG_male_2011.xlsx']

In [246]:
df = pd.ExcelFile('jp_FoodG_male_2012.xlsx').parse(0)

In [214]:
def droppingColIndex(df):
    lst = []
    for i in range(3,df.shape[1],3): 
        lst.append(i)
        lst.append(i+1)
    return lst

In [230]:
age = list(df.loc[5,:][df.loc[5,:].notna()])[2:]

In [231]:
df.dropna(axis = 0, inplace = True)

In [232]:
df.drop(df.columns[droppingColIndex(df)], axis = 1, inplace = True)

In [234]:
df.drop(['Unnamed: 1'], axis = 1, inplace = True)
df.columns = ['Elements','All']+age

In [247]:
df.head(10)

,平成24年 国民健康・栄養調査,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37
0,第1部 栄養素等摂取状況調査の結果,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,第５表の３ 食品群別摂取量 - 食品群、年齢階級別、平均値、標準偏差、中央値 - 全国補正値...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,１人１日当たり（ｇ）
5,NaN,食品群\n番号,総 数,NaN,NaN,1～6歳,NaN,NaN,7～14歳,NaN,...,NaN,70歳以上,NaN,NaN,（再掲）20歳以上,NaN,NaN,（再掲）75歳以上,NaN,NaN
6,NaN,NaN,平均値,標準偏差,中央値,平均値,標準偏差,中央値,平均値,標準偏差,...,中央値,平均値,標準偏差,中央値,平均値,標準偏差,中央値,平均値,標準偏差,中央値
7,解析対象者（人）,NaN,15084,NaN,NaN,846,NaN,NaN,1271,NaN,...,NaN,3015,NaN,NaN,12265,NaN,NaN,1828,NaN,NaN
8,総量,1～98,2190.03,765.132,2120.8,1227.35,366.426,1223.15,1924.9,493.468,...,2371.7,2275.4,719.668,2219.7,2290.94,758.95,2217.6,2190.13,693.987,2143
9,動物性食品,"48～76,79",343.206,188.606,310.6,325.16,174.968,312.3,541.577,204.132,...,298.5,317.505,172.388,296,316.139,168.028,289.2,306.45,168.618,284.3

In [ ]:
df.index[]

In [235]:
def parsingDemo(df): 
    age = list(df.loc[5,:][df.loc[5,:].notna()])[2:]
    df.dropna(axis = 0, inplace = True)
    
    df.drop(df.columns[droppingColIndex(df)], axis = 1, inplace = True)
    df.drop(['Unnamed: 1'], axis = 1, inplace = True)
    df.columns = ['Elements','All']+age
    return df

In [206]:
automatable = [i for i in os.listdir() if re.findall('2012|2013|2014|2015|2016',i)]

In [243]:
for i in automatable: 
    if re.findall('_male_',i):
        print(i)
        df = pd.ExcelFile(i).parse(0)
        age = list(df.loc[5,:][df.loc[5,:].notna()])[2:]
        df.dropna(axis = 0, inplace = True)

        df.drop(df.columns[droppingColIndex(df)], axis = 1, inplace = True)
        df.drop(['Unnamed: 1'], axis = 1, inplace = True)
        df.columns = ['Elements','All']+age

jp_FoodG_male_2012.xlsx
jp_FoodG_male_2013.xlsx

ValueError: Length mismatch: Expected axis has 13 elements, new values have 36 elements

In [244]:
age

['中央値',
 '平均値',
 '標準偏差',
 '中央値',
 '平均値',
 '標準偏差',
 '中央値',
 '平均値',
 '標準偏差',
 '中央値',
 '平均値',
 '標準偏差',
 '中央値',
 '平均値',
 '標準偏差',
 '中央値',
 '平均値',
 '標準偏差',
 '中央値',
 '平均値',
 '標準偏差',
 '中央値',
 '平均値',
 '標準偏差',
 '中央値',
 '平均値',
 '標準偏差',
 '中央値',
 '平均値',
 '標準偏差',
 '中央値',
 '平均値',
 '標準偏差',
 '中央値']

In [241]:
df

,平成25年国民健康・栄養調査,Unnamed: 2,Unnamed: 5,Unnamed: 8,Unnamed: 11,Unnamed: 14,Unnamed: 17,Unnamed: 20,Unnamed: 23,Unnamed: 26,Unnamed: 29,Unnamed: 32,Unnamed: 35
7,総量,2197.2,1202.49,1888.44,2182.14,2044.33,2128.99,2227.49,2344.85,2455.55,2341.47,2295.78,2242.85
8,動物性食品,346.014,326.354,524.883,420.856,334.943,314.072,303.643,317.286,333.819,333.093,324.203,322.952
9,植物性食品,1851.19,876.134,1363.55,1761.29,1709.38,1814.91,1923.84,2027.57,2121.73,2008.37,1971.58,1919.9
10,穀類,505.738,271.113,474.358,680.71,564.387,562.353,545.586,516.234,491.913,474.157,514.228,467.863
11,米・加工品,384.964,198.749,360.054,548.469,435.192,430.985,409.862,397.684,366.769,359.857,390.266,360.988
...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,塩,1.41308,0.709645,1.16146,1.55257,1.51722,1.64103,1.68772,1.63011,1.48825,1.17661,1.47752,1.08409
134,マヨネ－ズ,2.98407,2.04467,2.11178,3.56286,2.81575,3.79592,3.2239,3.9211,2.93511,2.48948,3.10337,2.25744
135,味噌,11.2165,5.74264,9.75255,8.75829,9.30256,9.28315,11.3515,11.7301,12.987,13.4162,11.873,14.2283
136,その他の調味料,67.3639,35.5234,61.921,73.3737,68.4,76.0897,78.5599,70.0811,70.0324,61.6605,69.6754,56.0795
137,香辛料・その他,0.375977,0.08934,0.302866,0.364,0.280952,0.384511,0.358333,0.414945,0.440909,0.441832,0.403169,0.357645